def check(string, ending, expected):
    result = solution(string, ending)
    test.assert_equals(result, expected, "Expected solution(" + repr(string) + ", " + repr(ending) + ") to return " + str(expected))
    
check("samurai", "ai", True)
check("sumo", "omo", False)
check("ninja", "ja", True)
check("sensei", "i", True)
check("samurai", "ra", False)
check("abc", "abcd", False)
check("abc", "abc", True)
check("abcabc", "bc", True)
check('ails', 'fails', False)
check('fails', 'ails', True)
check('this', 'fails', False)
check('abc', '', True)
check(':-)', ':-(', False)
check('!@#$%^&*() :-)', ':-)', True)
check('abc\n', 'abc', False)
